name: Release
on:
  push:
    tags:
      - v*
jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install build dependencies
        run: pip install --upgrade build check-manifest twine
      - name: Build
        run: |
          check-manifest
          python -m build
          python -m twine check dist/*
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true
