name: Test
on:
  - push
  - pull_request
jobs:
  test:
    strategy:
      matrix:
        python:
          - '3.12'
          - '3.13'
        platform:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}
      - name: Install test dependencies
        run: |
          pip install --upgrade build check-manifest twine black pytest pytest-cov
          pip install .
      - name: Lint
        run: black . --check
      - name: Build
        run: |
          check-manifest
          python -m build
          python -m twine check dist/*
      - name: Test and report coverage
        run: pytest --cov --cov-branch --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
